//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCfgBaudrateCmd.h
//  @ Date : 2014/11/5 ÐÇÆÚÈý
//  @ Author :
//
//


#if !defined(_CCFGBAUDRATECMD_H)
#define _CCFGBAUDRATECMD_H

#include "CfgProtocol.h"

class CCfgBaudrateCmd : public CCfgProtocol
{
    public:
        CCfgBaudrateCmd(CCommIntf* const pCommIntf, const DWORD dwBaudrate);
        virtual ~CCfgBaudrateCmd();

    protected:
        BOOL CreateSendCmd();
        BOOL CreateAckCmd();

    private:
        BYTE GetBaudrateIndex() const;

    private:
        DWORD m_dwBaudrate;
};

#endif  //_CCFGBAUDRATECMD_H



