//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCfgCommChannelCmd.cpp
//  @ Date : 2014/11/5 ÐÇÆÚÈý
//  @ Author :
//
//

#include "stdafx.h"
#include "CfgCommChannelCmd.h"
#include "../LogSystem.h"

CCfgCommChannelCmd::CCfgCommChannelCmd(CCommIntf* pCommIntf, const CHAR cCommChannelNum)
    : CCfgProtocol(pCommIntf)
{
    m_cCommChannelNum = cCommChannelNum;
}

CCfgCommChannelCmd::~CCfgCommChannelCmd()
{

}

BOOL CCfgCommChannelCmd::CreateSendCmd()
{
    CCmdFactory CmdFactory;
    m_pSendCmd = CmdFactory.createCmd(
                                 CProtocolConst::CMD_SET_COMM_CHANNEL,
                                 &m_cCommChannelNum,
                                 1);
    if (NULL == m_pSendCmd)
    {
        LOG_ERROR("Create the cmd of cfg for communication channel number, failed !");
        return FALSE;
    }


    return TRUE;
}

BOOL CCfgCommChannelCmd::CreateAckCmd()
{
    CCmdFactory CmdFactory;
    m_pAckCmd = CmdFactory.createEmptyAckCmd(m_pSendCmd->GetCmdDataBufferLen());
    if (NULL == m_pAckCmd)
    {
        LOG_ERROR("Create the null ack cmd for communication channel number, failed !");
        return FALSE;
    }

    return TRUE;
}


