//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCfgCommChannelCmd.h
//  @ Date : 2014/11/5 ÐÇÆÚÈý
//  @ Author :
//
//


#if !defined(_CCFGCOMMCHANNELCMD_H)
#define _CCFGCOMMCHANNELCMD_H

#include "CfgProtocol.h"

class CCfgCommChannelCmd : public CCfgProtocol
{
    public:
        CCfgCommChannelCmd(CCommIntf* pCommIntf, const CHAR cCommChannelNum);
        virtual ~CCfgCommChannelCmd();

    protected:
        BOOL CreateSendCmd();
        BOOL CreateAckCmd();

    private:
        UCHAR m_cCommChannelNum;
};

#endif  //_CCFGCOMMCHANNELCMD_H
