//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCfgMdlNetID.cpp
//  @ Date : 2014/11/5 ÐÇÆÚÈý
//  @ Author :
//
//

#include "stdafx.h"
#include "CfgMdlNetID.h"
#include "../LogSystem.h"

CCfgMdlNetID::CCfgMdlNetID(CCommIntf* pCommIntf, const USHORT& uMdlNetID)
    : CCfgProtocol(pCommIntf)
{
    m_uMdlNetID = uMdlNetID;
}

CCfgMdlNetID::~CCfgMdlNetID()
{

}

BOOL CCfgMdlNetID::CreateSendCmd()
{
    BYTE bCmdData[2] = { 0 };
    bCmdData[0] = SHORT_HIGH_BYTE(m_uMdlNetID);
    bCmdData[1] = SHORT_LOW_BYTE(m_uMdlNetID);

    CCmdFactory CmdFactory;
    m_pSendCmd = CmdFactory.createCmd(
                                 CProtocolConst::CMD_CFG_MDL_NET_ID,
                                 bCmdData,
                                 sizeof(bCmdData));
    if (NULL == m_pSendCmd)
    {
        LOG_ERROR(L"failed to create the cmd of cfg module net id.");
        return FALSE;
    }


    return TRUE;
}

BOOL CCfgMdlNetID::CreateAckCmd()
{
    CCmdFactory CmdFactory;
    m_pAckCmd = CmdFactory.createEmptyAckCmd(sizeof(m_uMdlNetID));
    if (NULL == m_pAckCmd)
    {
        LOG_ERROR("failed to create the null ack cmd of cfg module id.");
        return FALSE;
    }

    return TRUE;
}


