//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCfgProtocol.h
//  @ Date : 2014/10/29 ÐÇÆÚÈý
//  @ Author :
//
//


#if !defined(_CCFGPROTOCOL_H)
#define _CCFGPROTOCOL_H


#include "CmdFactory.h"
#include "AckCmdParser.h"
#include "CommIntf.h"

class CCfgProtocol
{
    public:
        CCfgProtocol(CCommIntf* pCommIntf);
        virtual ~CCfgProtocol();

        virtual BOOL SendCmd();
        virtual BOOL GetAckCmdData(PBYTE& pAckCmdData,
                                   DWORD& dwAckCmdDataLen) const;

    protected:
        virtual BOOL IsValidAckCmd();
        virtual BOOL CreateSendCmd() = 0;
        virtual BOOL CreateAckCmd() = 0;
        virtual BOOL CreateParser();

    private:
        virtual BOOL IsCmpCmd() const;
        void LogSentCmd() const;
        void LogReceivedAckCmd() const;
    protected:
        CCmd* m_pSendCmd;
        CCmd* m_pAckCmd;
        CAckCmdParser* m_pAckCmdParser;
        CCommIntf* m_pCommIntf;
};

#endif  //_CCFGPROTOCOL_H





