//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCommIntf.cpp
//  @ Date : 2014/10/29 ÐÇÆÚÈý
//  @ Author :
//
//

#include "stdafx.h"
#include "CommIntf.h"

CCommIntf::CCommIntf()
{
}

CCommIntf::~CCommIntf()
{

}

