//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CCommIntf.h
//  @ Date : 2014/10/29 ÐÇÆÚÈý
//  @ Author :
//
//


#if !defined(_CCOMMINTF_H)
#define _CCOMMINTF_H

#include "..\stdafx.h"


class CCommIntf
{
    public:
        CCommIntf();
        virtual ~CCommIntf();

        virtual BOOL SendData(PBYTE const pSendDataBuf, const DWORD dwLen) = 0;
        virtual BOOL ReadData(PBYTE const pReadDataBuf, const DWORD dwReadLen,
                              DWORD& dwReadBytes) = 0;
        virtual BOOL Close() = 0;

    protected:

        virtual BOOL IsOpen() = 0;
        virtual BOOL Open() = 0;
};

#endif  //_CCOMMINTF_H
