//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CComPortExplorer.h
//  @ Date : 2014/11/7 ÐÇÆÚÎå
//  @ Author :
//
//


#if !defined(_CCOMPORTEXPORER_H)
#define _CCOMPORTEXPORER_H

#include "../stdafx.h"
#include "../../Com/CnComm.h"

class CComPortExplorer
{
    public:
        CComPortExplorer(const HWND hWnd = NULL);
        virtual ~CComPortExplorer();

        BOOL GetCurLinkedDevCommPort(CMap<CString, LPCTSTR, DWORD, DWORD>& mapAllLinkedDeviceCom);

        DWORD GetPortNum(CString strComPortName);

        BOOL GetSysAllComPort(CStringArray& allSysCom);

    protected:
        BOOL GetSystemAllComPort();
        BOOL GetAllAvailableComPort(CMap<CString, LPCTSTR, DWORD, DWORD>& mapAllLinkedDeviceCom);

    private:
        CStringArray m_aAllSysCom;
        HWND m_hWnd;
};

#endif  //_CCOMPORTEXPORER_H


