//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CSearchCmd.h
//  @ Date : 2014/11/5 ÐÇÆÚÈý
//  @ Author :
//
//


#if !defined(_CSEARCHCMD_H)
#define _CSEARCHCMD_H

#include "CfgProtocol.h"

class CSearchCmd : public CCfgProtocol
{
    public:
        CSearchCmd(CCommIntf* const pCommIntf);
        virtual ~CSearchCmd();

    protected:
        BOOL CreateSendCmd();
        BOOL CreateAckCmd();
        BOOL IsValidAckCmd();
};

#endif  //_CSEARCHCMD_H







