//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CSearchCmd.cpp
//  @ Date : 2014/11/5 星期三
//  @ Author :
//
//

#include "stdafx.h"
#include "SearchCmd.h"
#include "../LogSystem.h"

CSearchCmd::CSearchCmd(CCommIntf* const pCommIntf)
    : CCfgProtocol(pCommIntf)
{

}

CSearchCmd::~CSearchCmd()
{

}

BOOL CSearchCmd::CreateSendCmd()
{
    CCmdFactory CmdFactory;
    BYTE btCmdData = 0;
    m_pSendCmd = CmdFactory.createCmd(CProtocolConst::CMD_CFG_SEARCH,
                                      &btCmdData,
                                      1);
    if (NULL == m_pSendCmd)
    {
        LOG_ERROR("When Creating the cmd of search, return the NULL's pointer for search, failed !");
        return FALSE;
    }

    return TRUE;
}

BOOL CSearchCmd::CreateAckCmd()
{
    CCmdFactory CmdFactory;
    m_pAckCmd = CmdFactory.createEmptyAckCmd(
                                CProtocolConst::SEARCH_ACK_CMD_DATA_LEN);
    if (NULL == m_pAckCmd)
    {
        LOG_ERROR("The ack cmd's pointer of search is NULL, failed !");
        return FALSE;
    }

    return TRUE;
}

BOOL CSearchCmd::IsValidAckCmd()
{
    ASSERT(NULL != m_pAckCmdParser);

    if (!m_pAckCmdParser->IsValidSearchAckCmd())
    {
        LOG_ERROR("The ack's cmd of search is invalid !");
        return FALSE;
    }

    if (m_pSendCmd->GetFrameHead() != m_pAckCmdParser->GetFrameHead())
    {
        LOG_ERROR("The Frame head of search for ack cmd :" <<
                  m_pAckCmdParser->GetFrameHead() <<
                  "is not equal to the frame head for search cmd : " <<
                  m_pSendCmd->GetFrameHead());
        return FALSE;
    }

    if (m_pSendCmd->GetCmdPreserveWord() != m_pAckCmdParser->GetPreserveword())
    {
        CString strLog;
        strLog.Format(
                        TEXT("应答搜索命令的保留字：%0X，与搜索命令的保留字：%0X，不相等！"),
                        m_pAckCmdParser->GetPreserveword(), m_pSendCmd->GetCmdPreserveWord());
        LOG_ERROR("The preserve word of ack cmd for search : " << m_pAckCmdParser->GetPreserveword() <<
                  "is not equal to the preserve word of search :" << m_pSendCmd->GetCmdPreserveWord() <<
                  ", failed !");
        return FALSE;
    }

    return TRUE;
}














