//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CSearchAckCmdDataParser.h
//  @ Date : 2014/10/29 星期三
//  @ Author :
//
//


#if !defined(_CSEARCHACKCMDDATAPARSER_H)
#define _CSEARCHACKCMDDATAPARSER_H

#include "../stdafx.h"
#include "CfgInfo.h"

class CSearchAckCmdDataParser
{
    public:
        CSearchAckCmdDataParser(PBYTE const pAckCmdData, const DWORD dwCmdDataLen);
        virtual ~CSearchAckCmdDataParser();

        DWORD GetCurBaudrate() const;
        DWORD GetMinBaudrate() const;
        DWORD GetMaxBaudrate() const;
        BYTE GetCurCommChannelNum() const;
        BYTE GetMaxCommChannelNum() const;
        DWORD GetCurTransSpeed() const;
        DWORD GetCurFrequency() const;
        DWORD GetID() const;
        PRODUCT_DATE GetProductDate() const;
        PRODUCT_VER GetHardwareVer() const;
        PRODUCT_VER GetSoftwareVer() const;
        USHORT GetProductType() const;
        USHORT GetMdlNetID() const;

    private:
        BOOL IsValidBaudrateIdx(const BYTE btBaudRateIdx) const;
    private:
        PBYTE m_pAckCmdData; // 由外部调用者负责释放
        DWORD m_dwCmdDataLen;
};

#endif  //_CSEARCHACKCMDDATAPARSER_H
